# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Hire Me"
  title = "Hire Me"
  weight = 10

[[main]]
  name = "How It Works"
  title = "How It Works"
  parent = "Hire Me"
  pageRef = "how-it-works"
  weight = 10

[[main]]
  name = "Resume"
  title = "Resume"
  parent = "Hire Me"
  pageRef = "resume"
  weight = 20

[[main]]
  name = "Availability"
  title = "Availability"
  parent = "Hire Me"
  pageRef = "availability"
  weight = 30
  

[[main]]
  name = "Client Docs"
  title = "Client Docs"
  parent = "Hire Me"
  url = "https://invited-tail-8f7.notion.site/Client-Docs-665a24baf6a149efbeb5814d6aca8ee4"
  weight = 30

[[main]]
  name = "FAQ"
  title = "FAQ"
  parent = "Hire Me"
  pageRef = "faq"
  weight = 40

[[main]]
  name = "ğŸ‘·ğŸ¼â€â™‚ï¸ About"
  title = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "ğŸ“ Tutorials"
  title = "Tutorials"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "ğŸ“ Blog"
  title = "Blog"
  pageRef = "blog"
  weight = 40

[[main]]
  name = "ğŸ“° Newsletter"
  title = "Newsletter"
  pageRef = "newsletter"
  weight = 50

[[main]]
  identifier = "civsoft"
  name = "CivSoft"
  pre = "civsoft"
  url = "https://civsoft.app/"
  weight = 60

# -- Subnav Menu --
# Displayed below main

[[subnavigation]]
  name = "Licensed in MA #56995"
  title = "Professional Engineer License, P.E."
  url = "https://elicensing21.mass.gov/CitizenAccess/GeneralProperty/LicenseeDetail.aspx?LicenseeNumber=56995&LicenseeType=Civil+Engineer"
  weight = 10

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20

 [[footer]]
   name = "Contact"
   pageRef = "contact"
   weight = 30






